use_frameworks!

target 'ModalWebViewController_Example' do
  pod 'ModalWebViewController', :path => '../'

  target 'ModalWebViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
